CREATE DATABASE IF NOT EXISTS TP4;
USE TP4;

CREATE TABLE IF NOT EXISTS myTable (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100)
);

INSERT INTO myTable (name) VALUES ('Alice'), ('Bob'), ('Charlie');
