name: tests unitaires

on: [push]

jobs:
  test1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.10"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Show branch and repo
        run: |
          echo "Nom branche: ${{ github.ref }}"
          echo "Runner OS: ${{ runner.os }}"

      - name: Set up Python for Demo
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # ou une autre version selon ton projet

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run tests
        run: |
          pytest TP1/test.py

